<?php

/**
 * Implements hook_form_alter().
 * 
 * Fixes an issue where the Newsletter block STILL redirects to the confirmation
 * page even though the webform is configured to not do that.
 */
function sronline_webform_form_alter(&$form, &$form_state, $form_id) {
  $matches = array();
  if (preg_match('/^webform_client_form_([0-9]+)/', $form_id, $matches)) {
    $form['#action'] .= '?destination=' . urlencode($_GET['q']);
  }
}
