<?php
// $Id: compact_forms.install,v 1.2.2.2 2011/01/09 05:32:11 sun Exp $

/**
 * @file
 * Installation functions for Compact Forms module.
 */

/**
 * Implements hook_uninstall().
 */
function compact_forms_uninstall() {
  variable_del('compact_forms_colons');
  variable_del('compact_forms_descriptions');
  variable_del('compact_forms_field_size');
  variable_del('compact_forms_ids');
  variable_del('compact_forms_stars');
}

